# Generated by Django 6.0.7 on 2026-07-17 02:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('payable', 'Payable'), ('receivable', 'Receivable')], max_length=12)),
                ('vendor', models.CharField(blank=True, default='', max_length=150)),
                ('client', models.CharField(blank=True, default='', max_length=150)),
                ('shipment_origin', models.CharField(blank=True, default='', max_length=120)),
                ('shipment_dest', models.CharField(blank=True, default='', max_length=120)),
                ('awb', models.CharField(blank=True, default='', max_length=60, verbose_name='AWB / BL number')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('PHP', 'Philippine Peso'), ('USD', 'US Dollar')], default='PHP', max_length=3)),
                ('status', models.CharField(choices=[('outstanding', 'Outstanding'), ('overdue', 'Overdue'), ('paid', 'Paid')], default='outstanding', max_length=12)),
                ('source', models.CharField(blank=True, default='Manual Entry', max_length=100, verbose_name='Source')),
                ('si_number', models.CharField(blank=True, default='', max_length=60, verbose_name='SI Number')),
                ('si_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('less_2307', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='LESS 2307')),
                ('soa_number', models.CharField(blank=True, default='', max_length=60, verbose_name='SOA Number')),
                ('soa_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='billing_bil_categor_2bc863_idx'), models.Index(fields=['status'], name='billing_bil_status_20b8a1_idx'), models.Index(fields=['invoice_date'], name='billing_bil_invoice_2b8381_idx')],
            },
        ),
    ]
