# Generated by Django 6.0.7 on 2026-07-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='credit_line',
            field=models.PositiveIntegerField(default=30, verbose_name='Credit line (days)'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='shipment_scope',
            field=models.CharField(choices=[('local', 'Local — city to city (Philippines)'), ('import', 'Import — country to city'), ('export', 'Export — city to country'), ('international', 'International — country to country')], default='local', max_length=15),
        ),
    ]
