# Generated by Django 6.0.7 on 2026-07-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billingrecord_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='si_entries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='soa_entries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
