# Generated by Django 6.0.7 on 2026-08-04 01:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billingrecord_si_entries_billingrecord_soa_entries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='carrier',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='er',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='E.R.'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='etd_eta',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ETD ETA'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='job_ref',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Job Ref #'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='mbl',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='MBL / MAWB'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='no_kgs_vol',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='No.s / Kgs. / Vol.'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='sold_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='sold_tin',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='TIN'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='vessel_flight',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Vessel / Flight'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='zero_rated',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, default='', max_length=60, verbose_name='Invoice No.')),
                ('sold_name', models.CharField(blank=True, default='', max_length=150)),
                ('sold_tin', models.CharField(blank=True, default='', max_length=20)),
                ('sold_address', models.CharField(blank=True, default='', max_length=255)),
                ('job_ref', models.CharField(blank=True, default='', max_length=60, verbose_name='Job Ref #')),
                ('so_no', models.CharField(blank=True, default='', max_length=60, verbose_name='SO No.')),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('credit_terms', models.CharField(blank=True, default='', max_length=60)),
                ('origin', models.CharField(blank=True, default='', max_length=120)),
                ('destination', models.CharField(blank=True, default='', max_length=120)),
                ('carrier', models.CharField(blank=True, default='', max_length=100)),
                ('vessel_flight', models.CharField(blank=True, default='', max_length=100)),
                ('no_kgs_vol', models.CharField(blank=True, default='', max_length=100)),
                ('hbl', models.CharField(blank=True, default='', max_length=100, verbose_name='HBL / HAWB')),
                ('mbl', models.CharField(blank=True, default='', max_length=100, verbose_name='MBL / MAWB')),
                ('etd_eta', models.CharField(blank=True, default='', max_length=100)),
                ('er', models.CharField(blank=True, default='', max_length=100, verbose_name='E.R.')),
                ('vatable_items', models.JSONField(blank=True, default=list)),
                ('non_vatable_items', models.JSONField(blank=True, default=list)),
                ('vatable_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('zero_rated_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('vat_exempt_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('less_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('less_withholding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
