# Generated by Django 6.0.7 on 2026-07-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_shipments', models.BooleanField(default=True)),
                ('notify_task_updates', models.BooleanField(default=True)),
                ('notify_overdue', models.BooleanField(default=True)),
                ('email_provider', models.CharField(default='gmail', max_length=30)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App settings',
                'verbose_name_plural': 'App settings',
            },
        ),
    ]
