# Generated by Django 6.0.7 on 2026-07-27 11:54

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=150)),
                ('company', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('shipment_type', models.CharField(blank=True, default='', max_length=30)),
                ('shipment_type_other', models.CharField(blank=True, default='', max_length=100)),
                ('mode', models.CharField(blank=True, default='', max_length=10)),
                ('origin', models.CharField(blank=True, default='', max_length=150)),
                ('destination', models.CharField(blank=True, default='', max_length=150)),
                ('cargo', models.TextField(blank=True, default='')),
                ('dangerous_goods', models.CharField(blank=True, default='', max_length=5)),
                ('quantity_type', models.CharField(blank=True, default='', max_length=20)),
                ('quantity_count', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('dg', 'Dangerous goods document (10.5)'), ('proof', 'Proof of goods (13)')], max_length=10)),
                ('file', models.FileField(upload_to=core.models.inquiry_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.inquiry')),
            ],
        ),
    ]
