# Generated by Django 6.0.7 on 2026-07-17 02:05

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrashedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trash_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item_type', models.CharField(choices=[('billing', 'Billing record'), ('agent', 'CRM agent / client')], max_length=20)),
                ('name', models.CharField(help_text='Display name shown in the Trash list', max_length=200)),
                ('original_id', models.CharField(help_text='Primary key of the record before deletion', max_length=64)),
                ('data', models.JSONField(help_text='Full snapshot of the record, used to restore it')),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
