# Generated by Django 6.0.7 on 2026-08-04 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trasheditem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Who deleted this record — each account only sees its own trash.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trashed_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
