# Generated by Django 6.0.7 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(
                blank=True,
                choices=[
                    ('CEO', 'CEO'),
                    ('Sales Account Executive', 'Sales Account Executive'),
                    ('Sales Account Manager', 'Sales Account Manager'),
                    ('Intern', 'Intern'),
                ],
                default='',
                max_length=40,
            ),
        ),
    ]
