# Generated by Django 6.0.7 on 2026-07-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Sales Account Manager', 'Sales Account Manager'), ('Sales Account Executive', 'Sales Account Executive'), ('Intern', 'Intern')], default='', max_length=40),
        ),
    ]
