from decimal import Decimal
from django.conf import settings
from django.db import models
from django.utils import timezone


class BillingRecord(models.Model):
    """
    A single payable or receivable invoice/ledger entry.
    Mirrors the front-end's `billingRecords` array 1:1.

    Total = SI Amount − LESS 2307 + SOA Amount
    (international/USD records skip SI & LESS 2307 — no VAT applies)
    """

    class Category(models.TextChoices):
        PAYABLE = "payable", "Payable"
        RECEIVABLE = "receivable", "Receivable"

    class Status(models.TextChoices):
        OUTSTANDING = "outstanding", "Outstanding"
        OVERDUE = "overdue", "Overdue"
        PAID = "paid", "Paid"

    class Currency(models.TextChoices):
        PHP = "PHP", "Philippine Peso"
        USD = "USD", "US Dollar"

    class ShipmentScope(models.TextChoices):
        LOCAL = "local", "Local — city to city (Philippines)"
        IMPORT = "import", "Import — country to city"
        EXPORT = "export", "Export — city to country"
        INTERNATIONAL = "international", "International — country to country"

    category = models.CharField(max_length=12, choices=Category.choices)
    vendor = models.CharField(max_length=150, blank=True, default="")
    client = models.CharField(max_length=150, blank=True, default="")

    # shipment lane, e.g. "Manila -> Bangkok"
    shipment_origin = models.CharField(max_length=120, blank=True, default="")
    shipment_dest = models.CharField(max_length=120, blank=True, default="")
    shipment_scope = models.CharField(max_length=15, choices=ShipmentScope.choices, default=ShipmentScope.LOCAL)
    awb = models.CharField("AWB / BL number", max_length=60, blank=True, default="")

    invoice_date = models.DateField(null=True, blank=True)
    # Employees enter a credit line (days) rather than typing a due date by hand;
    # due_date is invoice_date + credit_line, recomputed on save.
    credit_line = models.PositiveIntegerField("Credit line (days)", default=30)
    due_date = models.DateField(null=True, blank=True)

    currency = models.CharField(max_length=3, choices=Currency.choices, default=Currency.PHP)
    status = models.CharField(max_length=12, choices=Status.choices, default=Status.OUTSTANDING)
    source = models.CharField("Source", max_length=100, blank=True, default="Manual Entry")

    # invoice breakdown
    si_number = models.CharField("SI Number", max_length=60, blank=True, default="")
    si_amount = models.DecimalField(max_digits=14, decimal_places=2, default=Decimal("0.00"))
    # Vatable line items under this SI (e.g. handling, pickup, crating) — each
    # is {"desc": "...", "amount": 123.45}. si_amount is their sum, kept as
    # a separate field for fast querying/reporting.
    si_entries = models.JSONField(default=list, blank=True)
    less_2307 = models.DecimalField("LESS 2307", max_digits=14, decimal_places=2, default=Decimal("0.00"))
    soa_number = models.CharField("SOA Number", max_length=60, blank=True, default="")
    soa_amount = models.DecimalField(max_digits=14, decimal_places=2, default=Decimal("0.00"))
    # Non-vatable line items under this SOA (e.g. labor, food) — same shape as si_entries.
    soa_entries = models.JSONField(default=list, blank=True)

    # amount is derived (si - less_2307 + soa) but stored for fast querying/reporting
    amount = models.DecimalField(max_digits=14, decimal_places=2, default=Decimal("0.00"))

    # Job reference — shown on the printable SI/SOA sheet in place of the
    # SI/SOA number when present. Separate from si_number/soa_number since
    # a job ref is assigned by the client, not generated by us.
    job_ref = models.CharField("Job Ref #", max_length=60, blank=True, default="")

    # Printable-sheet fields — these mirror the New Invoice modal's TIN,
    # address, carrier/vessel, and cargo-reference inputs so they can be
    # printed straight onto the pre-printed SI/SOA pad.
    sold_tin = models.CharField("TIN", max_length=20, blank=True, default="")
    sold_address = models.CharField("Address", max_length=255, blank=True, default="")
    mbl = models.CharField("MBL / MAWB", max_length=100, blank=True, default="")
    carrier = models.CharField(max_length=100, blank=True, default="")
    vessel_flight = models.CharField("Vessel / Flight", max_length=100, blank=True, default="")
    no_kgs_vol = models.CharField("No.s / Kgs. / Vol.", max_length=100, blank=True, default="")
    er = models.CharField("E.R.", max_length=100, blank=True, default="")
    etd_eta = models.CharField("ETD ETA", max_length=100, blank=True, default="")
    zero_rated = models.DecimalField(max_digits=14, decimal_places=2, default=Decimal("0.00"))
    discount = models.DecimalField(max_digits=14, decimal_places=2, default=Decimal("0.00"))

    # Who entered this invoice — powers the small avatar column in the
    # Billing table. Null for records imported before this field existed.
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name="billing_records_created",
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["category"]),
            models.Index(fields=["status"]),
            models.Index(fields=["invoice_date"]),
        ]

    def __str__(self):
        who = self.vendor if self.category == self.Category.PAYABLE else self.client
        return f"{self.get_category_display()} · {who or 'Untitled'} · {self.amount} {self.currency}"

    @property
    def shipment(self):
        if self.shipment_origin and self.shipment_dest:
            return f"{self.shipment_origin} \u2192 {self.shipment_dest}"
        return self.shipment_origin or self.shipment_dest or ""

    def recompute_amount(self):
        si = self.si_amount if self.currency == self.Currency.PHP else Decimal("0.00")
        less = self.less_2307 if si else Decimal("0.00")
        self.amount = si - less + self.soa_amount

    def recompute_status(self):
        """Auto-flag overdue invoices whose due date has passed and are unpaid."""
        if self.status == self.Status.PAID:
            return
        if self.due_date and self.due_date < timezone.localdate():
            self.status = self.Status.OVERDUE
        elif self.status == self.Status.OVERDUE:
            self.status = self.Status.OUTSTANDING

    def recompute_due_date(self):
        """Employees enter a credit line (days), not a due date — mirrors the
        front-end's New Invoice modal so the backend stays the source of truth
        even if a client sends an inconsistent due_date."""
        if self.invoice_date:
            self.due_date = self.invoice_date + timezone.timedelta(days=self.credit_line or 0)

    def save(self, *args, **kwargs):
        self.recompute_amount()
        self.recompute_due_date()
        self.recompute_status()
        super().save(*args, **kwargs)


class Quotation(models.Model):
    """
    A standalone, savable/printable SI/SOA sheet — created directly from the
    Quotation page rather than from a Billing ledger entry. Field names
    mirror the front-end's quotationToApi()/quotationFromApi() exactly.
    """
    invoice_no = models.CharField("Invoice No.", max_length=60, blank=True, default="")
    sold_name = models.CharField(max_length=150, blank=True, default="")
    sold_tin = models.CharField(max_length=20, blank=True, default="")
    sold_address = models.CharField(max_length=255, blank=True, default="")
    job_ref = models.CharField("Job Ref #", max_length=60, blank=True, default="")
    so_no = models.CharField("SO No.", max_length=60, blank=True, default="")
    issued_date = models.DateField(null=True, blank=True)
    credit_terms = models.CharField(max_length=60, blank=True, default="")
    origin = models.CharField(max_length=120, blank=True, default="")
    destination = models.CharField(max_length=120, blank=True, default="")
    carrier = models.CharField(max_length=100, blank=True, default="")
    vessel_flight = models.CharField(max_length=100, blank=True, default="")
    no_kgs_vol = models.CharField(max_length=100, blank=True, default="")
    hbl = models.CharField("HBL / HAWB", max_length=100, blank=True, default="")
    mbl = models.CharField("MBL / MAWB", max_length=100, blank=True, default="")
    etd_eta = models.CharField(max_length=100, blank=True, default="")
    er = models.CharField("E.R.", max_length=100, blank=True, default="")

    # Each entry is {"desc": "...", "amount": 123.45}
    vatable_items = models.JSONField(default=list, blank=True)
    non_vatable_items = models.JSONField(default=list, blank=True)

    vatable_sales = models.DecimalField(max_digits=14, decimal_places=2, default=Decimal("0.00"))
    zero_rated_sales = models.DecimalField(max_digits=14, decimal_places=2, default=Decimal("0.00"))
    vat_exempt_sales = models.DecimalField(max_digits=14, decimal_places=2, default=Decimal("0.00"))
    less_discount = models.DecimalField(max_digits=14, decimal_places=2, default=Decimal("0.00"))
    less_withholding = models.DecimalField(max_digits=14, decimal_places=2, default=Decimal("0.00"))

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name="quotations_created",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"Quotation {self.invoice_no or self.pk} — {self.sold_name or 'Untitled'}"
