# Generated by Django 6.0.7 on 2026-07-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bell', help_text='lucide-icon name', max_length=40)),
                ('color', models.CharField(default='var(--gold)', help_text='CSS color/var used by the bell icon', max_length=30)),
                ('text', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('target_view', models.CharField(blank=True, default='', max_length=40)),
                ('target_bill_type', models.CharField(blank=True, default='', max_length=20)),
                ('target_bill_status', models.CharField(blank=True, default='', max_length=20)),
                ('target_row_id', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
